language: node_js

node_js:
  - 5.6.0

sudo: required

env:
  DOCKER_COMPOSE_VERSION: 1.8.0-rc1

services:
  - docker

install:
  - sudo apt-get update
  - sudo apt-get install docker-engine
  - curl -L https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose

  - docker pull node:4
  - npm install

before_script:
  - docker -v
  - docker-compose -v

after_script:
  - cat stitch-debug.log
  - cat test/resources/test-microservices/microserviceRoot/docker-compose.yml
