language: node_js

node_js:
  - 5.6.0

sudo: required

services:
  - docker

install:
  - docker pull node:4
  - npm install

before_script:
  - docker -v
  - docker-compose -v

after_script:
  - cat stitch-debug.log
  - cat test/resources/test-microservices/microserviceRoot/docker-compose.yml
